//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/2000_2_new_split.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
cached.wad
gfx.wad
pldecal.wad
sprites/fire.spr
opfor.wad
maps/2000_2_new_split.bsp
