//res file generated by ds-servers.com
//visit ds-servers.com
maps/big_city.res
overviews/big_city.txt
overviews/big_city.bmp
sound/big_city/stepup.wav
sound/big_city/water_flowing3.wav
sound/big_city/windy.wav
halflife.wad
gfx/env/morningbk.tga
gfx/env/morningdn.tga
gfx/env/morningft.tga
gfx/env/morninglf.tga
gfx/env/morningrt.tga
gfx/env/morningup.tga