//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/kitkat_beach_ext.html
halflife.wad
models/skeleton.mdl
sprites/fire.spr
models/3dm_seagull.mdl
sound/beach/gull2.wav
sound/beach/wavebig.wav
sound/beach/ahh1.wav
sound/beach/homer2.wav
sound/beach/moan2.wav
sound/beach/human01.wav
sound/beach/latinsummer2k.wav
sound/beach/box.wav
sound/beach/girlsigh.wav
gfx/env/sunset02bk.tga
gfx/env/sunset02dn.tga
gfx/env/sunset02ft.tga
gfx/env/sunset02lf.tga
gfx/env/sunset02rt.tga
gfx/env/sunset02up.tga
maps/kitkat_beach_ext.bsp
