//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/zm_2000_2_frozen_v3.html
halflife.wad
sprites/fire.spr
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
sound/ambience/sparks.wav
sound/ambience/bigwarning.wav
sound/ambience/hammer.wav
sound/ambience/aliencave1.wav
sound/ambience/fc_dog2.wav
sound/bullchicken/bc_idle3.wav
sound/zm_2000_2/horror3.wav
sound/zm_2000_2/horror1.wav
sound/zm_2000_2/red.wav
maps/zm_2000_2_frozen_v3.bsp
