//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/2000_2_new_droidedit.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
cached.wad
gfx.wad
pldecal.wad
sound/ambience/alien_beacon.wav
sprites/fire.spr
sprites/flyball.spr
opfor.wad
models/2000_xmas/gesch1.mdl
models/droidbanner.mdl
maps/2000_2_new_droidedit.bsp
