//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/2000_2_no_mortal.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
models/bigrat.mdl
models/can.mdl
models/skeleton.mdl
sound/debris/beamstart1.wav
sound/debris/beamstart2.wav
sound/ambience/biggun2.wav
sprites/muzzleflash2.spr
maps/2000_2_no_mortal.bsp
