//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/2020_egypt_dm.html
halflife.wad
sound/ambience/wind2.wav
sprites/fire.spr
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
sound/ambience/wind1.wav
sound/ambience/alienwind2.wav
sound/ambience/windtunnel.wav
sound/ambience/wind_tunnel1.wav
maps/2020_egypt_dm.bsp
