//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/2_moonshine_home.html
halflife.wad
gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
gfx.wad
sprites/wsplash3.spr
maps/2_moonshine_home.bsp
