//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/$2000$.html
sprites/glow01.spr
gfx/env/catalanebk.tga
gfx/env/catalanedn.tga
gfx/env/catalaneft.tga
gfx/env/catalanelf.tga
gfx/env/catalanert.tga
gfx/env/catalaneup.tga
overviews/$2000$.bmp
maps/$2000$.bsp
maps/$2000$.txt
